// ui/theme_loader.h — parsed app themes (task 7.1, 7.2, design D11).
//
// theme_defs.inc (generated by cmake/extract_themes.cmake) provides the
// SetupXxxStyle() function definitions; this module exposes them as a list
// of named entries the menubar can render.
#pragma once

#include <string>
#include <vector>

namespace diffcue::ui {

struct ThemeEntry {
    std::string name;        // display name, e.g. "Dark", "ForestGreen"
    void (*apply)();         // calls the SetupXxxStyle() function
};

// Return all themes parsed from thirdparty/theme.txt. The first entry is the
// default (applied at startup when prefs.app_theme is empty/unmatched).
const std::vector<ThemeEntry>& load_themes();

// Apply the theme by name. No-op if not found.
void apply_theme(const std::string& name);

}  // namespace diffcue::ui
